-- Create a table for public profiles (extends auth.users)
create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  full_name text,
  plan_tier text default 'free', -- 'free', 'monthly', 'yearly', 'lifetime'
  stripe_customer_id text,
  updated_at timestamp with time zone,
  
  primary key (id)
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for resumes
create table public.resumes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  content jsonb default '{}'::jsonb,
  strength integer default 0,
  thumbnail text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.resumes enable row level security;

create policy "Users can view their own resumes."
  on resumes for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own resumes."
  on resumes for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own resumes."
  on resumes for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own resumes."
  on resumes for delete
  using ( auth.uid() = user_id );

-- Trigger to handle new user signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, plan_tier)
  values (new.id, new.raw_user_meta_data->>'full_name', 'free');
  return new;
end;
$$;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
