
import * as pdfjsLib from 'pdfjs-dist';
import mammoth from 'mammoth';

// Configure Worker
pdfjsLib.GlobalWorkerOptions.workerSrc = '/pdf.worker.min.mjs';

export const parseResume = async (file) => {
    const fileType = file.type;
    const fileName = file.name.toLowerCase();

    try {
        if (fileType === 'application/pdf' || fileName.endsWith('.pdf')) {
            return await parsePdf(file);
        } else if (
            fileType === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' ||
            fileName.endsWith('.docx')
        ) {
            return await parseDocx(file);
        } else if (fileType === 'text/plain' || fileName.endsWith('.txt')) {
            return await parseTxt(file);
        } else {
            throw new Error(`Formato de arquivo não suportado: ${fileType || fileName}`);
        }
    } catch (error) {
        console.error("Resume Parsing Error:", error);
        throw new Error("Falha ao ler o arquivo. Verifique se não está corrompido.");
    }
};

const parsePdf = async (file) => {
    const arrayBuffer = await file.arrayBuffer();
    const pdf = await pdfjsLib.getDocument(arrayBuffer).promise;

    // --- CV Fácil Round-Trip: detect embedded structured data ---
    // PDFs generated by this app store the full resume JSON in the
    // document's Keywords property. If present, use it directly —
    // no regex parsing needed and no data loss.
    try {
        const metadata = await pdf.getMetadata();
        const keywords = metadata?.info?.Keywords || '';
        if (keywords.startsWith('cvfacil-structured:')) {
            // The JSON was stored with encodeURIComponent to safely handle
            // parentheses, accented chars, and other special characters.
            const encoded = keywords.slice('cvfacil-structured:'.length);
            const data = JSON.parse(decodeURIComponent(encoded));
            if (data && data.personalInfo && Array.isArray(data.experience)) {
                return data;
            }
        }
    } catch (_) {
        // Metadata read failed — fall through to text extraction
    }

    // --- Fallback: text extraction for external PDFs ---
    let fullText = '';

    for (let i = 1; i <= pdf.numPages; i++) {
        const page = await pdf.getPage(i);
        const textContent = await page.getTextContent();

        let lastY = null;
        let pageText = '';

        for (const item of textContent.items) {
            // item.transform is [scaleX, skewY, skewX, scaleY, tx, ty]
            const currentY = item.transform[5];

            if (lastY !== null && Math.abs(currentY - lastY) > 5) {
                pageText += '\n';
            } else if (pageText.length > 0 && !pageText.endsWith('\n')) {
                // Add space between words on same line
                pageText += ' ';
            }

            pageText += item.str;
            lastY = currentY;
        }

        fullText += pageText + '\n';
    }

    return extractDataFromText(fullText);
};

const parseDocx = async (file) => {
    const arrayBuffer = await file.arrayBuffer();
    const result = await mammoth.extractRawText({ arrayBuffer: arrayBuffer });
    return extractDataFromText(result.value);
};

const parseTxt = async (file) => {
    const text = await file.text();
    return extractDataFromText(text);
};

const extractDataFromText = (text) => {
    // Normalize text (preserve lines for some parsing, but clean excessive spaces)
    const normalizedText = text.replace(/\r\n/g, '\n').replace(/\t/g, ' ').replace(/\x00/g, ''); // Remove null bytes
    const lines = normalizedText.split('\n').filter(line => line.trim().length > 0);
    const cleanedGlobal = normalizedText.replace(/\s+/g, ' ').trim();

    const sections = {
        personalInfo: { fullName: '', role: '', email: '', phone: '', location: '', summary: '', linkedin: '', nationality: '' },
        experience: [],
        education: [],
        skills: [],
        languages: []
    };

    // --- 1. Global Extractors ---
    const emailMatch = cleanedGlobal.match(/([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9_-]+)/);
    if (emailMatch) sections.personalInfo.email = emailMatch[0];

    const phoneMatch = cleanedGlobal.match(/(\(?\d{2}\)?\s?\d{4,5}-?\d{4})/);
    if (phoneMatch) sections.personalInfo.phone = phoneMatch[0];

    const linkedinMatch = cleanedGlobal.match(/linkedin\.com\/in\/[\w-]+/i);
    if (linkedinMatch) sections.personalInfo.linkedin = `https://www.${linkedinMatch[0]}`;

    // Portfolio: look for the labeled field "Portfólio: <url>" produced by pdfGenerator,
    // then fall back to known portfolio domains.
    const portfolioLabelMatch = cleanedGlobal.match(/portf[oó]lio[:\s]+([^\s,]+)/i);
    if (portfolioLabelMatch) {
        sections.personalInfo.portfolio = portfolioLabelMatch[1];
    } else {
        const portfolioDomainMatch = cleanedGlobal.match(/https?:\/\/(?!(?:www\.)?linkedin\.com|(?:www\.)?github\.com)[\w.-]+\/[\w.~:/?#[\]@!$&'()*+,;=%-]+/i);
        if (portfolioDomainMatch) sections.personalInfo.portfolio = portfolioDomainMatch[0];
    }

    // GitHub
    const githubMatch = cleanedGlobal.match(/github\.com\/[\w-]+/i);
    if (githubMatch) sections.personalInfo.github = `https://www.${githubMatch[0]}`;

    // --- 2. Name + Role Extraction ---
    // Name is the first meaningful line; role/cargo is the second line if it
    // looks like a job title (short, no contact info, no section header).
    const sectionHeaderPattern = /^(OBJETIVO|OBJECTIVE|RESUMO|SUMMARY|SOBRE MIM|ABOUT|PERFIL|EXPERIÊNCIA|EXPERIENCE|EDUCAÇÃO|EDUCATION|FORMAÇÃO|HABILIDADES|SKILLS|IDIOMAS|LANGUAGES|CONTATO|CONTACT|INFORMAÇÃO)/i;
    const contactLinePattern = /@|linkedin\.com|github\.com|\(\d{2}\)|\d{4,5}-\d{4}/i;

    if (lines.length > 0) {
        const firstLine = lines[0].trim();
        if (firstLine.length > 3 && !/página|page|currículo|cv/i.test(firstLine)) {
            sections.personalInfo.fullName = firstLine;
        }
    }

    if (lines.length > 1) {
        const secondLine = lines[1].trim();
        if (
            secondLine.length > 2 &&
            secondLine.length < 80 &&
            !sectionHeaderPattern.test(secondLine) &&
            !contactLinePattern.test(secondLine)
        ) {
            sections.personalInfo.role = secondLine;
        }
    }

    // --- 3. Section Extraction (Strict Headers) ---
    // We expect headers to be at the start of a line or surrounded by newlines
    const headers = {
        contact: /(?:\n|^)\s*(INFORMAÇÃO DE CONTATO|CONTACT INFO|CONTATO)/i,
        summary: /(?:\n|^)\s*(OBJETIVO|OBJECTIVE|RESUMO|SUMMARY|SOBRE MIM|ABOUT|PERFIL)/i,
        experience: /(?:\n|^)\s*(EXPERIÊNCIA|EXPERIENCE|WORK HISTORY|HISTÓRICO PROFISSIONAL)/i,
        education: /(?:\n|^)\s*(EDUCAÇÃO|EDUCATION|FORMAÇÃO|ACADEMIC|HISTÓRICO ACADÊMICO)/i,
        skills: /(?:\n|^)\s*(HABILIDADES|SKILLS|COMPETÊNCIAS|TECHNICAL SKILLS)/i,
        languages: /(?:\n|^)\s*(IDIOMAS|LANGUAGES)/i
    };

    const findSectionIndex = (regex) => {
        const match = normalizedText.match(regex);
        return match ? match.index : -1;
    };

    const foundHeaders = [
        { key: 'contact', index: findSectionIndex(headers.contact) },
        { key: 'summary', index: findSectionIndex(headers.summary) },
        { key: 'experience', index: findSectionIndex(headers.experience) },
        { key: 'education', index: findSectionIndex(headers.education) },
        { key: 'skills', index: findSectionIndex(headers.skills) },
        { key: 'languages', index: findSectionIndex(headers.languages) }
    ].filter(h => h.index !== -1).sort((a, b) => a.index - b.index);

    const getSectionContent = (key) => {
        const headerObj = foundHeaders.find(h => h.key === key);
        if (!headerObj) return '';

        const nextHeaderIndex = foundHeaders.findIndex(h => h === headerObj);
        const nextHeader = foundHeaders[nextHeaderIndex + 1];

        const content = nextHeader
            ? normalizedText.substring(headerObj.index, nextHeader.index)
            : normalizedText.substring(headerObj.index);

        // The regex match includes the leading \n, so after split('\n'):
        //   [0] = "" (empty, before the \n)
        //   [1] = "OBJETIVO" (the header title itself)
        //   [2+] = actual content
        // Filtering empty lines first makes [0] always the header → slice(1) removes it cleanly.
        const sectionLines = content.split('\n').filter(l => l.trim().length > 0);
        return sectionLines.slice(1).join('\n').trim();
    };

    // Populate Sections
    const summaryRaw = getSectionContent('summary');
    if (summaryRaw) sections.personalInfo.summary = summaryRaw.replace(/\s+/g, ' ').trim();

    const experienceRaw = getSectionContent('experience');
    if (experienceRaw) sections.experience = parseExperienceItems(experienceRaw);

    const educationRaw = getSectionContent('education');
    if (educationRaw) sections.education = parseEducationItems(educationRaw);

    const skillsRaw = getSectionContent('skills');
    if (skillsRaw) {
        // Split by bullets, commas or newlines
        const list = skillsRaw.split(/[,•\n]/)
            .map(s => s.trim())
            .filter(s => s.length > 2 && !/HABILIDADES|SKILLS/i.test(s));

        // Deduplicate and limit
        sections.skills = [...new Set(list)].slice(0, 15);
    }

    // Languages
    // Handles three formats produced by PDF extraction:
    //   "Inglês - Avançado"  (single line with separator)
    //   "Inglês\nAvançado"   (two separate lines — happens in CV Fácil PDFs because
    //                         name and level are drawn 4mm apart, which exceeds the
    //                         newline threshold of the pdfjs text extractor)
    //   "Inglês"             (name only, no level)
    const languagesRaw = getSectionContent('languages');
    if (languagesRaw) {
        // Known level keywords — used to detect the two-line pattern
        const levelPattern = /^(nativo|fluente|avan[çc]ado|intermedi[áa]rio|b[áa]sico|nativa|native|fluent|advanced|intermediate|basic|beginner|proficient|conversational|elementary|c1|c2|b1|b2|a1|a2)/i;
        // Exclude section header words that sometimes leak through
        const headerPattern = /^(IDIOMAS|LANGUAGES|IDIOMA|LANGUAGE)$/i;

        const langLines = languagesRaw
            .split('\n')
            .map(l => l.trim())
            .filter(l => l.length > 1 && !headerPattern.test(l));

        const result = [];
        let i = 0;
        while (i < langLines.length && result.length < 6) {
            const line = langLines[i];
            const next = langLines[i + 1] || '';

            if (line.includes(' - ')) {
                // "Inglês - Avançado"
                const parts = line.split(' - ');
                result.push({ id: result.length, name: parts[0].trim(), level: parts.slice(1).join(' - ').trim() });
                i++;
            } else if (line.includes(':')) {
                // "Inglês: Avançado"
                const parts = line.split(':');
                result.push({ id: result.length, name: parts[0].trim(), level: parts[1]?.trim() || '' });
                i++;
            } else if (next && levelPattern.test(next)) {
                // Two-line: name on this line, level on the next
                result.push({ id: result.length, name: line, level: next });
                i += 2;
            } else if (levelPattern.test(line)) {
                // Orphaned level line — attach to the previous entry if it has no level yet
                if (result.length > 0 && !result[result.length - 1].level) {
                    result[result.length - 1].level = line;
                }
                i++;
            } else {
                result.push({ id: result.length, name: line, level: '' });
                i++;
            }
        }
        sections.languages = result;
    }

    const nationalityMatch = cleanedGlobal.match(/(brasileiro|brasileira|brazilian)/i);
    if (nationalityMatch) {
        const nat = nationalityMatch[0].toLowerCase();
        sections.personalInfo.nationality = nat.charAt(0).toUpperCase() + nat.slice(1);
    }

    return sections;
};

// Start of Logic: Experience Parsing
const parseExperienceItems = (text) => {
    const items = [];
    const lines = text.split('\n').filter(l => l.trim());

    let currentItem = null;

    // Improved Regex to match "Mon Year - Mon Year" or "Mon Year"
    // Matches start of line or generally isolated dates
    const dateRangeRegex = /((?:jan|fev|mar|abr|mai|jun|jul|ago|set|out|nov|dez|january|february|march|april|may|june|july|august|september|october|november|december|\d{2})\/?\s?\d{2,4}\s?[-–to]\s?(?:jan|fev|mar|abr|mai|jun|jul|ago|set|out|nov|dez|january|february|march|april|may|june|july|august|september|october|november|december|\d{2}|present|presente|atual)\/?\s?\d{0,4})/i;

    lines.forEach(line => {
        const dateMatch = line.match(dateRangeRegex);

        if (dateMatch) {
            // New Item Detected by Date
            if (currentItem) items.push(currentItem);

            currentItem = {
                company: '',
                position: '',
                location: '',
                startDate: '',
                endDate: '',
                isCurrent: false,
                description: ''
            };

            // Parse Dates
            const fullDateStr = dateMatch[0];
            const dates = fullDateStr.split(/[-–to]/);
            currentItem.startDate = dates[0].trim();
            currentItem.endDate = dates[1] ? dates[1].trim() : '';
            if (/present|atual/i.test(currentItem.endDate)) currentItem.isCurrent = true;

            // Handle Text on the Same Line as Date
            const remaining = line.replace(fullDateStr, '').trim();

            if (remaining.length > 0) {
                // Heuristic: Short text is likely Role/Company. Long text is Description.
                if (remaining.length < 50) {
                    currentItem.position = remaining;
                } else {
                    // Too long, likely description
                    currentItem.description += remaining + '\n';
                }
            }
        } else {
            // Line without Date
            if (currentItem) {
                // If Item is fresh (no description yet), try to fill Position/Company from short lines
                const isShort = line.length < 60;

                if (isShort && !currentItem.description) {
                    if (!currentItem.position) {
                        currentItem.position = line;
                    } else if (!currentItem.company) {
                        currentItem.company = line;
                    } else {
                        // We have both, maybe Location?
                        if (/Brazil|SP|MG|RJ|Remote|Remoto/i.test(line)) {
                            currentItem.location = line;
                        } else {
                            // Otherwise, likely bullet point start
                            currentItem.description += line + '\n';
                        }
                    }
                } else {
                    // Description
                    currentItem.description += line + '\n';
                }
            }
            // Text before any date found is ignored (headers, stray lines)
        }
    });

    if (currentItem) items.push(currentItem);

    // Fallback
    if (items.length === 0 && text.length > 20) {
        return [{ company: 'Experiência (Não separada)', position: '', description: text }];
    }

    return items;
};

const parseEducationItems = (text) => {
    const items = [];
    const lines = text.split('\n').filter(l => l.trim());
    let currentItem = null;
    const dateRegex = /\d{4}/;

    lines.forEach(line => {
        if (dateRegex.test(line) && line.length < 40) {
            if (currentItem) items.push(currentItem);
            currentItem = { school: '', degree: '', startDate: '', endDate: '' };

            const years = line.match(/\d{4}/g);
            if (years) {
                if (years.length >= 1) currentItem.startDate = years[0];
                if (years.length >= 2) currentItem.endDate = years[1];
            }
        } else {
            if (currentItem) {
                if (!currentItem.degree) currentItem.degree = line;
                else if (!currentItem.school) currentItem.school = line;
            } else {
                // Start first item if valid text
                if (line.length > 3) {
                    currentItem = { school: '', degree: line, startDate: '', endDate: '' };
                }
            }
        }
    });

    if (currentItem) items.push(currentItem);
    if (items.length === 0 && text.length > 10) {
        return [{ school: 'Instituição (Editar)', degree: text.substring(0, 100), startDate: '' }];
    }
    return items;
};
